<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bed_Type_Skytron_NYU_Spine</name>
   <tag></tag>
   <elementGuidId>ff09f118-6da4-458a-8e84-34f6fb7d8577</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu-']/div[2]/ul/li[5][text()='Skytron']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//div[@id='menu-']/div[2]/ul/li[5][text()='Skytron']</value>
   </webElementXpaths>
</WebElementEntity>
