<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ImplantsImplant Name SYNERGY Short Stem_2cb069</name>
   <tag></tag>
   <elementGuidId>7ab15aaa-e737-4046-9b30-4bb7eb69ad9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss900</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ImplantsImplant Name ​SYNERGY Short Stem - Smith &amp; Nephew - Larry Astwood (Stage-NYU) - Standard DemandDeleteImplant SelectedRepRep ConfirmationTray Info DeliveryImplant Delivery StatusTray Delivery StatusSterilization StatusANTHOLOGY Hip System (Stem)Smith &amp; Nephew Larry Astwood (Stage-NYU)UnconfirmedUnconfirmedUnconfirmedUnconfirmedBIOLOX delta Ceramic Femoral HeadStryker Shelby Dapuzzo (Stage-NYU)UnconfirmedUnconfirmedUnconfirmedUnconfirmedR3 Multi Hole Acetabular ShellSmith &amp; Nephew Larry Astwood (Stage-NYU)UnconfirmedUnconfirmedUnconfirmedUnconfirmedConfirm Implants AddedBonegrafts and BiologicsBonegrafts and Biologics Products​DeleteBonegrafts Products SelectedRepStatusNo bonegraft products have been added.Monitoring ProductsMonitoring Products​DeleteMonitoring Products SelectedRepStatusNo monitoring products have been added.Ancillary ProductsAncillary Products​DeleteAncillary Products SelectedRepStatusNo ancillary products have been added.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;jss373 sc-htoDjs gOIOCa&quot;]/div[@class=&quot;jss373 jss396 jss386 jss390&quot;]/div[@class=&quot;jss373 jss374 jss382 jss390 jss410&quot;]/div[@class=&quot;jss298 jss301 jss299 jss855&quot;]/div[@class=&quot;jss900&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Case'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]</value>
   </webElementXpaths>
</WebElementEntity>
