<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CommentsCommentUserDateSCHEDULER COMMEN_690883</name>
   <tag></tag>
   <elementGuidId>eb421127-aaf9-4a0f-807a-3c46594261ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss423</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CommentsCommentUserDateSCHEDULER COMMENT 1Cathy Lee (Stage-NYU)03/26/2020 9:48:02 AMSCHEDULER COMMENT 1Cathy Lee (Stage-NYU)03/26/2020 9:48:04 AMhiCathy Lee (Stage-NYU)03/26/2020 9:48:05 AMhiThomas Youm (Stage-NYU)03/26/2020 10:02:02 AMSURGEON COMMENT 1Thomas Youm (Stage-NYU)03/26/2020 10:02:04 AMSURGEON COMMENT 1Thomas Youm (Stage-NYU)03/26/2020 10:02:05 AMComment​Add Comment</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;jss108 sc-htoDjs gOIOCa&quot;]/div[@class=&quot;jss108 jss131 jss121 jss125&quot;]/div[@class=&quot;jss108 jss109 jss117 jss125 jss145&quot;]/div[@class=&quot;jss33 jss36 jss34 jss387&quot;]/div[@class=&quot;jss423&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amend Case'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
